name: Playwright Smoke Test CI

on:
  push:
    branches: [feature/VikashKadamata-QloyalCodeTest]
  pull_request:
    branches: [feature/VikashKadamata-QloyalCodeTest]

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Tests with HTML Report
        run: npm run test:headless 
        env:
          WEATHERBIT_API_KEY: ${{ secrets.WEATHERBIT_API_KEY }}
          username_standard: ${{ secrets.username_standard }}
          password_standard: ${{ secrets.password_standard }}

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
