# GitHub Actions workflow for running Playwright tests
name: Playwright Tests

on:
  push:
    branches: [ feature/VikashKadamata-QloyalCodeTest ]
  pull_request:
    branches: [ feature/VikashKadamata-QloyalCodeTest ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
